(() => {
  'use strict';
  const nav=document.querySelector('nav');
  const navWrap=nav?.querySelector('.wrap');
  const links=nav?.querySelector('.links');
  if(!nav||!navWrap)return;
  const skip=document.createElement('a');skip.className='neusic-skip';skip.href='#top';skip.textContent='Skip to Neusic';document.body.prepend(skip);
  const menu=document.createElement('button');menu.className='neusic-menu-button';menu.type='button';menu.setAttribute('aria-label','Open navigation');menu.setAttribute('aria-expanded','false');menu.textContent='☰';
  navWrap.insertBefore(menu,navWrap.querySelector('.actions'));
  const drawer=document.createElement('div');drawer.className='neusic-mobile-menu';drawer.setAttribute('aria-label','Mobile navigation');
  (links?[...links.querySelectorAll('a')]:[]).forEach(link=>drawer.append(link.cloneNode(true)));
  [['Studio','./studio/'],['Wave Loom','./wave-loom/']].forEach(([label,href])=>{const a=document.createElement('a');a.href=href;a.textContent=label;drawer.append(a)});
  document.body.append(drawer);
  menu.addEventListener('click',()=>{const open=drawer.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'×':'☰'});
  drawer.addEventListener('click',event=>{if(event.target.closest('a')){drawer.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){drawer.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'}});
  const launch=document.createElement('div');launch.className='neusic-mobile-launch';launch.innerHTML='<a href="./studio/">OPEN STUDIO ▶</a><a href="./wave-loom/">WAVE LOOM ⌁</a>';document.body.append(launch);
  const updateNav=()=>nav.classList.toggle('scrolled',scrollY>24);updateNav();addEventListener('scroll',updateNav,{passive:true});
  const targets=[...document.querySelectorAll('section .section-head,.feature,.flow-card,.road,.theme-picker,.brain,.cta-box')];
  if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){targets.forEach(el=>el.classList.add('reveal-ready'));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.08});targets.forEach(el=>observer.observe(el));}else targets.forEach(el=>el.classList.add('revealed'));
})();