'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Headquarters = { totals: Record<string, number>; activity: { id: number; title: string; description?: string; created_at: string; event_type: string }[]; companies: { id: number; name: string; status: string; tasks: { status: string; title: string }[]; approvals: { status: string; title: string }[] }[] };
type Briefing = { objective: string; status: string; agents: { name: string; task: string }[]; timestamp: string };

export default function ExecutiveBriefingPage() {
  const [headquarters, setHeadquarters] = useState<Headquarters | null>(null);
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  useEffect(() => { Promise.all([fetch('/api/headquarters').then((r) => r.json()), fetch('/api/briefing').then((r) => r.json())]).then(([hq, b]) => { setHeadquarters(hq); setBriefing(b); }).catch(() => undefined); }, []);
  const blocked = useMemo(() => headquarters?.companies.flatMap((company) => company.tasks.filter((task) => task.status === 'blocked').map((task) => ({ ...task, company: company.name }))) || [], [headquarters]);
  const pending = useMemo(() => headquarters?.companies.flatMap((company) => company.approvals.filter((approval) => approval.status === 'pending').map((approval) => ({ ...approval, company: company.name }))) || [], [headquarters]);

  return <main className="mx-auto max-w-7xl px-4 py-6 md:px-6 lg:px-8">
    <section className="cyvora-glass-strong rounded-3xl p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[0.24em] text-violet-200/75">CEO workspace</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white md:text-5xl">Executive Briefing</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">A separate surface for objectives, risks, opportunities, blocked work, recommendations, and company health.</p></div><Link href="/command-center" className="cyvora-chip inline-flex min-h-11 items-center px-4 text-sm text-cyan-100">Open Command Center</Link></div></section>

    <section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Companies" value={headquarters?.totals.companies ?? '—'} /><Metric label="Agents" value={headquarters?.totals.agents ?? '—'} /><Metric label="Tasks" value={headquarters?.totals.tasks ?? '—'} /><Metric label="Pending decisions" value={pending.length} tone="amber" /><Metric label="Blocked work" value={blocked.length} tone={blocked.length ? 'rose' : 'emerald'} /></section>

    <section className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]">
      <article className="cyvora-glass rounded-3xl p-5 md:p-6"><p className="text-[10px] uppercase tracking-[0.22em] text-cyan-200/70">Morning brief</p><h2 className="mt-2 text-2xl font-semibold text-white">{briefing?.objective || 'No active objective'}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{pending.length ? `${pending.length} founder decision${pending.length === 1 ? '' : 's'} need attention.` : 'No approvals are waiting.'} {blocked.length ? `${blocked.length} task${blocked.length === 1 ? '' : 's'} are blocked.` : 'No blocked work is reported.'}</p><div className="mt-5 rounded-2xl border border-violet-300/10 bg-violet-300/[0.03] p-4"><p className="text-[9px] uppercase tracking-[0.18em] text-violet-200/70">Recommended next action</p><p className="mt-2 text-sm leading-6 text-slate-300">{pending.length ? `Review “${pending[0].title}” in Command Center before expanding execution.` : blocked.length ? `Resolve “${blocked[0].title}” in ${blocked[0].company}.` : 'Use Executive AI to prepare the next company blueprint or mission.'}</p></div></article>
      <article className="cyvora-glass rounded-3xl p-5 md:p-6"><p className="text-[10px] uppercase tracking-[0.22em] text-emerald-200/70">Company health</p><div className="mt-4 space-y-3">{(headquarters?.companies || []).slice(0, 6).map((company) => { const companyBlocked = company.tasks.filter((task) => task.status === 'blocked').length; const companyPending = company.approvals.filter((approval) => approval.status === 'pending').length; return <div key={company.id} className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-white">{company.name}</strong><span className={`text-[9px] uppercase ${companyBlocked ? 'text-rose-200' : companyPending ? 'text-amber-200' : 'text-emerald-200'}`}>{companyBlocked ? 'Blocked' : companyPending ? 'Needs decision' : 'Healthy'}</span></div><p className="mt-2 text-[10px] text-slate-500">{company.tasks.length} tasks · {companyPending} approvals</p></div>; })}</div></article>
    </section>

    <section className="mt-4 grid gap-4 lg:grid-cols-3"><BriefCard title="Risks" tone="rose" items={blocked.map((item) => `${item.company}: ${item.title}`)} empty="No blocked tasks are reported." /><BriefCard title="Founder decisions" tone="amber" items={pending.map((item) => `${item.company}: ${item.title}`)} empty="No pending approvals." /><BriefCard title="Opportunities" tone="violet" items={['Use Company Engine templates to launch reusable operating structures.', 'Assign specialist agents from the registry instead of recreating prompts.', 'Keep mock providers and connectors enabled until monetization readiness.']} empty="No opportunities." /></section>

    <section className="mt-4 cyvora-glass rounded-3xl p-5 md:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.22em] text-cyan-200/70">Recent events</p><h2 className="mt-2 text-xl font-semibold text-white">What changed</h2></div><Link href="/history" className="text-xs text-cyan-200">Full history</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{(headquarters?.activity || []).slice(0, 8).map((event) => <div key={event.id} className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4"><strong className="text-xs text-slate-200">{event.title}</strong><p className="mt-1 text-[10px] leading-5 text-slate-500">{event.description || event.event_type}</p></div>)}</div></section>
  </main>;
}

function Metric({ label, value, tone = 'cyan' }: { label: string; value: string | number; tone?: 'cyan' | 'amber' | 'rose' | 'emerald' }) { const color = tone === 'amber' ? 'text-amber-200' : tone === 'rose' ? 'text-rose-200' : tone === 'emerald' ? 'text-emerald-200' : 'text-cyan-100'; return <div className="cyvora-tactile rounded-2xl p-4"><span className="text-[9px] uppercase tracking-[0.16em] text-slate-600">{label}</span><strong className={`mt-2 block text-xl ${color}`}>{value}</strong></div>; }
function BriefCard({ title, items, empty, tone }: { title: string; items: string[]; empty: string; tone: 'rose' | 'amber' | 'violet' }) { const color = tone === 'rose' ? 'text-rose-200' : tone === 'amber' ? 'text-amber-200' : 'text-violet-200'; return <article className="cyvora-glass rounded-3xl p-5"><p className={`text-[10px] uppercase tracking-[0.2em] ${color}`}>{title}</p><div className="mt-4 space-y-2">{items.length ? items.slice(0, 5).map((item) => <p key={item} className="rounded-xl border border-white/[0.05] bg-white/[0.02] p-3 text-xs leading-5 text-slate-400">{item}</p>) : <p className="text-xs text-slate-500">{empty}</p>}</div></article>; }
