'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import NavBar from '@/components/NavBar';

export default function CompanyDetailPage() {
  const params = useParams();
  const id = params.id as string;
  const [company, setCompany] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!id) return;
    fetch(`/api/companies/${id}`)
      .then((res) => {
        if (!res.ok) throw new Error('Failed to load company');
        return res.json();
      })
      .then(setCompany)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [id]);

  const totals = useMemo(() => {
    if (!company) return { departments: 0, teams: 0, agents: 0, tasks: 0, approvals: 0 };
    const orgTotals = company.departments?.reduce(
      (acc: any, department: any) => {
        acc.departments += 1;
        acc.teams += department.teams?.length || 0;
        for (const team of department.teams || []) acc.agents += team.agents?.length || 0;
        return acc;
      },
      { departments: 0, teams: 0, agents: 0 }
    );
    return {
      ...orgTotals,
      tasks: company.tasks?.length || 0,
      approvals: company.approvals?.filter((approval: any) => approval.status === 'pending').length || 0,
    };
  }, [company]);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#070b12] text-white">
        <NavBar />
        <main className="mx-auto max-w-7xl px-4 py-10 text-slate-400">Loading company...</main>
      </div>
    );
  }

  if (error || !company) {
    return (
      <div className="min-h-screen bg-[#070b12] text-white">
        <NavBar />
        <main className="mx-auto max-w-7xl px-4 py-10 text-rose-200">Error: {error || 'Not found'}</main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#070b12] text-white">
      <NavBar />

      <main className="mx-auto max-w-7xl px-4 py-6 md:px-6 lg:px-8">
        <section className="rounded-2xl border border-white/10 bg-slate-950/75 p-5 shadow-2xl shadow-blue-950/20 md:p-7">
          <div className="flex flex-wrap items-start justify-between gap-5">
            <div className="flex gap-4">
              <div className="h-14 w-14 rounded-2xl" style={{ backgroundColor: company.brand_color || '#38bdf8' }} />
              <div>
                <p className="text-sm font-medium uppercase tracking-[0.22em] text-cyan-300">Company Dashboard</p>
                <h1 className="mt-2 text-3xl font-semibold md:text-5xl">{company.name}</h1>
                <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">{company.description}</p>
              </div>
            </div>
            <Link href="/headquarters" className="rounded-xl border border-white/10 px-4 py-2 text-sm text-slate-200 transition hover:bg-white/5">
              Headquarters
            </Link>
          </div>
        </section>

        <section className="mt-6 grid gap-4 md:grid-cols-5">
          <Stat label="Departments" value={totals.departments} />
          <Stat label="Teams" value={totals.teams} />
          <Stat label="Agents" value={totals.agents} />
          <Stat label="Tasks" value={totals.tasks} />
          <Stat label="Approvals" value={totals.approvals} />
        </section>

        <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_420px]">
          <div className="rounded-2xl border border-white/10 bg-slate-950/70 p-5 md:p-6">
            <div className="mb-5">
              <h2 className="text-lg font-semibold">Active tasks</h2>
              <p className="mt-1 text-sm text-slate-400">Workflow stages generated by the Executive AI</p>
            </div>
            <div className="space-y-3">
              {company.tasks?.length ? (
                company.tasks.map((task: any) => (
                  <div key={task.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div>
                        <p className="text-sm font-medium text-white">{task.title}</p>
                        <p className="mt-1 text-xs leading-5 text-slate-400">{task.description}</p>
                      </div>
                      <span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs text-cyan-100">
                        {task.workflow_stage}
                      </span>
                    </div>
                    <p className="mt-3 text-xs text-slate-500">
                      {task.status} · {task.priority} priority · {task.assigned_agent || 'Executive AI'}
                    </p>
                  </div>
                ))
              ) : (
                <p className="rounded-xl border border-dashed border-white/10 bg-black/20 p-5 text-sm text-slate-400">No tasks yet.</p>
              )}
            </div>
          </div>

          <div className="space-y-6">
            <div className="rounded-2xl border border-white/10 bg-slate-950/70 p-5 md:p-6">
              <h2 className="text-lg font-semibold">Approval queue</h2>
              <div className="mt-4 space-y-3">
                {company.approvals?.length ? (
                  company.approvals.map((approval: any) => (
                    <div key={approval.id} className="rounded-xl border border-amber-300/20 bg-amber-300/10 p-4">
                      <p className="text-sm font-medium text-amber-100">{approval.title}</p>
                      <p className="mt-1 text-xs leading-5 text-amber-50/80">{approval.summary}</p>
                      <p className="mt-2 text-xs text-amber-100/70">{approval.status} · {approval.risk_level} risk</p>
                    </div>
                  ))
                ) : (
                  <p className="text-sm text-slate-400">No approvals waiting.</p>
                )}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-slate-950/70 p-5 md:p-6">
              <h2 className="text-lg font-semibold">Outputs</h2>
              <div className="mt-4 space-y-3">
                {company.outputs?.length ? (
                  company.outputs.slice(0, 5).map((output: any) => (
                    <div key={output.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
                      <p className="text-sm font-medium">{output.title}</p>
                      <p className="mt-1 text-xs text-slate-400">{output.output_type} · {output.status}</p>
                    </div>
                  ))
                ) : (
                  <p className="text-sm text-slate-400">No outputs generated yet.</p>
                )}
              </div>
            </div>
          </div>
        </section>

        <section className="mt-6 rounded-2xl border border-white/10 bg-slate-950/70 p-5 md:p-6">
          <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 className="text-lg font-semibold">Operating structure</h2>
              <p className="mt-1 text-sm text-slate-400">Departments, teams, and assigned agents</p>
            </div>
            <span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 text-xs text-emerald-200">
              {company.status || 'active'}
            </span>
          </div>

          <div className="space-y-5">
            {company.departments?.length === 0 && (
              <p className="rounded-xl border border-dashed border-white/10 bg-black/20 p-5 text-sm text-slate-400">No departments yet.</p>
            )}
            {company.departments?.map((department: any) => (
              <div key={department.id} className="rounded-2xl border border-white/10 bg-black/20 p-4">
                <div className="border-b border-white/10 pb-3">
                  <h3 className="font-semibold text-cyan-100">{department.name}</h3>
                  <p className="mt-1 text-sm text-slate-400">{department.description}</p>
                </div>
                <div className="mt-4 grid gap-4 lg:grid-cols-2">
                  {department.teams?.map((team: any) => (
                    <div key={team.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
                      <h4 className="text-sm font-medium">{team.name}</h4>
                      <p className="mt-1 text-xs leading-5 text-slate-400">{team.description}</p>
                      <div className="mt-3 flex flex-wrap gap-2">
                        {team.agents?.length ? (
                          team.agents.map((agent: any) => (
                            <span key={agent.id} className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs text-cyan-100">
                              {agent.agent_name}
                            </span>
                          ))
                        ) : (
                          <span className="text-xs text-slate-500">No agents assigned</span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        <div className="mt-6">
          <Link href="/companies" className="text-sm text-cyan-200 underline-offset-4 hover:underline">
            Back to Companies
          </Link>
        </div>
      </main>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-slate-950/70 p-5">
      <p className="text-3xl font-semibold text-white">{value}</p>
      <p className="mt-1 text-sm text-slate-400">{label}</p>
    </div>
  );
}
