(() => {
  'use strict';
  const canvas=document.getElementById('loomCanvas'),ctx=canvas.getContext('2d'),frame=document.getElementById('loomFrame'),sampleShelf=document.getElementById('sampleShelf');
  const TAU=Math.PI*2,POINTS=96,ROOTS=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
  const SCALE_STEPS={minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],dorian:[0,2,3,5,7,9,10],pentatonic:[0,3,5,7,10],chromatic:[0,1,2,3,4,5,6,7,8,9,10,11]},STORE='neusic-wave-loom-lab-v1';
  const state={
    points:Array.from({length:POINTS},(_,i)=>{const t=i/(POINTS-1);return Math.sin(t*TAU*2)*.27+Math.sin(t*TAU*5+.8)*.09+Math.sin(t*TAU*9)*.035;}),
    basePoints:null,nodes:Array.from({length:8},(_,i)=>({id:`node-${i+1}`,x:.11+i*.105,y:.46+Math.sin(i*1.48)*.19,velocity:88+(i*7)%34})),
    loopStart:.055,loopEnd:.945,tempo:112,root:0,scale:'minor',harmonics:.58,density:.46,space:.32,morph:0,tool:'sculpt',selectedNode:0,zeroPerc:true,livePreview:true,playing:false,pointer:null,samples:[],
    mic:{stream:null,recorder:null,chunks:[],analyser:null,data:null,startTime:0},
    audio:{ctx:null,master:null,dry:null,wet:null,delay:null,feedback:null,compressor:null,nextLoopTime:0,timer:0,loopDuration:0,periodicWave:null},animation:0,playhead:0
  };
  state.basePoints=state.points.slice();
  const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  function setStatus(message,live=state.playing){$('statusMessage').textContent=message;$('engineStatus').textContent=live?'ENGINE ACTIVE':'ENGINE IDLE';$('engineLed').classList.toggle('live',live);}
  function saveState(){try{localStorage.setItem(STORE,JSON.stringify({points:state.points,nodes:state.nodes,loopStart:state.loopStart,loopEnd:state.loopEnd,tempo:state.tempo,root:state.root,scale:state.scale,harmonics:state.harmonics,density:state.density,space:state.space,morph:state.morph,zeroPerc:state.zeroPerc}));}catch(_){}}
  function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(!saved)return;if(Array.isArray(saved.points)&&saved.points.length===POINTS)state.points=saved.points.map(Number);if(Array.isArray(saved.nodes))state.nodes=saved.nodes.map((node,index)=>({id:node.id||`node-${index+1}`,x:clamp(Number(node.x)||.1,.02,.98),y:clamp(Number(node.y)||.5,.04,.96),velocity:clamp(Number(node.velocity)||96,1,127)}));['loopStart','loopEnd','harmonics','density','space','morph'].forEach(key=>{if(Number.isFinite(Number(saved[key])))state[key]=Number(saved[key]);});state.tempo=clamp(Number(saved.tempo)||112,40,220);state.root=clamp(Number(saved.root)||0,0,11);state.scale=SCALE_STEPS[saved.scale]?saved.scale:'minor';state.zeroPerc=saved.zeroPerc!==false;state.basePoints=state.points.slice();}catch(_){}}
  function resize(){const rect=frame.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
  function geometry(){const rect=canvas.getBoundingClientRect();return{w:rect.width,h:rect.height,cx:rect.width/2,cy:rect.height/2,amp:Math.max(70,rect.height*.29)};}
  function waveYAt(x){const raw=clamp(x,0,1)*(POINTS-1),i=Math.floor(raw),f=raw-i;return lerp(state.points[i]||0,state.points[Math.min(POINTS-1,i+1)]||0,f);}
  function canvasToNormalized(x,y){const g=geometry();return{x:clamp(x/g.w,0,1),y:clamp(y/g.h,0,1),wave:clamp((g.cy-y)/g.amp,-1,1)};}
  function drawGrid(g){ctx.save();ctx.strokeStyle='rgba(75,190,205,.065)';ctx.lineWidth=1;for(let i=1;i<16;i++){const x=i*g.w/16;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,g.h);ctx.stroke();}for(let i=1;i<8;i++){const y=i*g.h/8;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(g.w,y);ctx.stroke();}ctx.strokeStyle='rgba(89,241,255,.17)';ctx.beginPath();ctx.moveTo(0,g.cy);ctx.lineTo(g.w,g.cy);ctx.stroke();ctx.restore();}
  function drawBoundary(x,side,g){const px=x*g.w,width=Math.max(15,g.w*.018),grad=ctx.createLinearGradient(px-width,0,px+width,0);grad.addColorStop(0,'rgba(160,240,255,0)');grad.addColorStop(.5,'rgba(182,247,255,.17)');grad.addColorStop(1,'rgba(160,240,255,0)');ctx.fillStyle=grad;ctx.fillRect(px-width,0,width*2,g.h);ctx.strokeStyle='rgba(180,247,255,.62)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px,0);ctx.lineTo(px,g.h);ctx.stroke();ctx.fillStyle='rgba(175,242,250,.74)';ctx.font='700 7px "JetBrains Mono", monospace';ctx.textAlign=side==='left'?'left':'right';ctx.fillText(side==='left'?'LOOP IN':'LOOP OUT',px+(side==='left'?7:-7),g.h-15);}
  function buildPath(g,depth=0,phase=0){ctx.beginPath();for(let i=0;i<POINTS;i++){const x=i/(POINTS-1),px=x*g.w,perspective=(x-.5)*depth*6,point=state.points[i],flutter=Math.sin(phase*1.7+i*.43)*.008*state.harmonics,py=g.cy-(point+flutter)*g.amp+depth*8+perspective;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}}
  function drawWave(g,time){ctx.save();ctx.globalCompositeOperation='lighter';[{depth:-2,color:'rgba(155,108,255,.13)',blur:24,width:7},{depth:2,color:'rgba(101,255,156,.10)',blur:22,width:6},{depth:0,color:'rgba(41,243,255,.18)',blur:28,width:10}].forEach(layer=>{ctx.shadowColor=layer.color;ctx.shadowBlur=layer.blur;ctx.strokeStyle=layer.color;ctx.lineWidth=layer.width;buildPath(g,layer.depth,time*.0008);ctx.stroke();});const grad=ctx.createLinearGradient(0,0,g.w,0);grad.addColorStop(0,'#34f5ff');grad.addColorStop(.32,'#7ffff0');grad.addColorStop(.58,'#a978ff');grad.addColorStop(.82,'#4effa1');grad.addColorStop(1,'#2ddcff');ctx.shadowColor='#38eaff';ctx.shadowBlur=17;ctx.strokeStyle=grad;ctx.lineWidth=2.1;buildPath(g,0,time*.001);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.68)';ctx.lineWidth=.55;buildPath(g,0,time*.001);ctx.stroke();ctx.restore();}
  function drawCrossings(g){let count=0;ctx.save();for(let i=1;i<POINTS;i++){const a=state.points[i-1],b=state.points[i];if((a<=0&&b>0)||(a>=0&&b<0)){const f=Math.abs(a)/(Math.abs(a)+Math.abs(b)),x=((i-1)+f)/(POINTS-1);if(x<state.loopStart||x>state.loopEnd)continue;count++;const px=x*g.w;ctx.fillStyle='rgba(101,255,156,.75)';ctx.shadowColor='#65ff9c';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(px,g.cy,2.1,0,TAU);ctx.fill();}}ctx.restore();$('crossCount').textContent=`${count} CROSSINGS`;return count;}
  function nodePosition(node){const g=geometry();return{x:node.x*g.w,y:node.y*g.h};}
  function drawNodes(g){state.nodes.forEach((node,index)=>{if(node.x<state.loopStart||node.x>state.loopEnd)return;const p=nodePosition(node),selected=index===state.selectedNode;ctx.save();ctx.globalCompositeOperation='lighter';const glow=ctx.createRadialGradient(p.x-3,p.y-4,1,p.x,p.y,selected?26:20);glow.addColorStop(0,'rgba(255,255,255,.96)');glow.addColorStop(.18,selected?'rgba(255,79,200,.95)':'rgba(138,116,255,.95)');glow.addColorStop(.5,selected?'rgba(255,79,200,.24)':'rgba(41,243,255,.22)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(p.x,p.y,selected?28:23,0,TAU);ctx.fill();ctx.shadowColor=selected?'#ff4fc8':'#7f7cff';ctx.shadowBlur=12;ctx.fillStyle=selected?'#ff9edc':'#c3eaff';ctx.beginPath();ctx.arc(p.x,p.y,selected?7:6,0,TAU);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,selected?10:9,0,TAU);ctx.stroke();ctx.restore();ctx.fillStyle='rgba(173,221,228,.7)';ctx.font='700 6px "JetBrains Mono",monospace';ctx.textAlign='center';ctx.fillText(String(index+1).padStart(2,'0'),p.x,p.y-15);});$('nodeCount').textContent=`${state.nodes.length} NODE${state.nodes.length===1?'':'S'}`;}
  function drawPlayhead(g){if(!state.playing)return;const x=lerp(state.loopStart,state.loopEnd,state.playhead)*g.w;ctx.save();ctx.strokeStyle='rgba(255,255,255,.8)';ctx.shadowColor='#fff';ctx.shadowBlur=7;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,g.h);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(x-4,0);ctx.lineTo(x+4,0);ctx.lineTo(x,7);ctx.fill();ctx.restore();}
  function draw(){const g=geometry(),time=performance.now();ctx.clearRect(0,0,g.w,g.h);const bg=ctx.createRadialGradient(g.cx,g.cy,0,g.cx,g.cy,Math.max(g.w,g.h)*.75);bg.addColorStop(0,'rgba(7,35,43,.82)');bg.addColorStop(.45,'rgba(2,12,17,.94)');bg.addColorStop(1,'#010407');ctx.fillStyle=bg;ctx.fillRect(0,0,g.w,g.h);drawGrid(g);drawBoundary(state.loopStart,'left',g);drawBoundary(state.loopEnd,'right',g);drawWave(g,time);drawCrossings(g);drawNodes(g);drawPlayhead(g);}
  function animate(){if(state.playing&&state.audio.ctx&&state.audio.loopDuration){const elapsed=state.audio.ctx.currentTime-(state.audio.nextLoopTime-state.audio.loopDuration);state.playhead=((elapsed%state.audio.loopDuration)+state.audio.loopDuration)%state.audio.loopDuration/state.audio.loopDuration;}draw();updateInputMeter();state.animation=requestAnimationFrame(animate);}
  function selectedNode(){return state.nodes[state.selectedNode]||null;}
  function midiForNode(node){const scale=SCALE_STEPS[state.scale]||SCALE_STEPS.minor,normalized=1-node.y,degree=Math.round(normalized*20),octave=2+Math.floor(degree/scale.length);return 12*(octave+1)+state.root+scale[degree%scale.length];}
  function midiName(midi){return ROOTS[((midi%12)+12)%12]+(Math.floor(midi/12)-1);}
  function updateInspector(){const node=selectedNode();if(!node){$('selectedNodeLabel').textContent='NO NODE';['pitchOut','timeOut','velocityOut','colorOut'].forEach(id=>$(id).textContent='—');$('nodeVelocity').disabled=true;$('deleteNodeBtn').disabled=true;return;}$('nodeVelocity').disabled=false;$('deleteNodeBtn').disabled=false;const step=Math.round((node.x-state.loopStart)/Math.max(.001,state.loopEnd-state.loopStart)*16),beat=Math.floor(step/4)+1,sub=step%4+1;$('selectedNodeLabel').textContent=`NODE ${String(state.selectedNode+1).padStart(2,'0')}`;$('pitchOut').textContent=midiName(midiForNode(node));$('timeOut').textContent=`${String(beat).padStart(2,'0')}.${sub}.00`;$('velocityOut').textContent=node.velocity;$('colorOut').textContent=state.selectedNode%2?'VIOLET':'CYAN';$('nodeVelocity').value=node.velocity;}
  function updateControls(){$('tempoInput').value=state.tempo;$('tempoReadout').textContent=state.tempo;$('rootSelect').selectedIndex=state.root;$('scaleSelect').value=state.scale;$('zeroPerc').checked=state.zeroPerc;$('livePreview').checked=state.livePreview;['harmonics','density','space','morph'].forEach(id=>{const value=Math.round(state[id]*100);$(id).value=value;$(id).nextElementSibling.textContent=value;});updateLoopReadout();updateInspector();}
  function updateLoopReadout(){const start=Math.round(state.loopStart*16),end=Math.round(state.loopEnd*16),fmt=v=>`${String(Math.floor(v/4)+1).padStart(2,'0')}.${v%4+1}`;$('loopReadout').textContent=`${fmt(start)} — ${fmt(end)}`;}
  function hitTest(x,y){const g=geometry(),boundaryThreshold=18;if(Math.abs(x-state.loopStart*g.w)<boundaryThreshold)return{type:'boundary',side:'start'};if(Math.abs(x-state.loopEnd*g.w)<boundaryThreshold)return{type:'boundary',side:'end'};for(let i=state.nodes.length-1;i>=0;i--){const p=nodePosition(state.nodes[i]);if(Math.hypot(x-p.x,y-p.y)<18)return{type:'node',index:i};}return{type:'wave'};}
  function sculptAt(x,y,strength=1){const n=canvasToNormalized(x,y),center=n.x*(POINTS-1),radius=7+state.density*10;for(let i=0;i<POINTS;i++){const d=(i-center)/radius,weight=Math.exp(-d*d*2.2);state.points[i]=clamp(lerp(state.points[i],n.wave,weight*.48*strength),-.96,.96);}state.audio.periodicWave=null;if(state.livePreview)previewAt(n.y);saveState();}
  let previewGate=0;function previewAt(normalizedY){const now=performance.now();if(now-previewGate<70)return;previewGate=now;scheduleVoice({y:normalizedY,velocity:70,x:.5},ensureAudio().currentTime+.005,.11);}
  function pointerPosition(event){const r=canvas.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top};}
  canvas.addEventListener('pointerdown',event=>{event.preventDefault();canvas.setPointerCapture?.(event.pointerId);const p=pointerPosition(event),hit=hitTest(p.x,p.y);state.pointer={...hit,last:p};if(hit.type==='node'){state.selectedNode=hit.index;updateInspector();if(state.tool==='sculpt')state.tool='nodes';}else if(hit.type==='wave'&&state.tool==='sculpt')sculptAt(p.x,p.y);});
  canvas.addEventListener('pointermove',event=>{if(!state.pointer)return;const p=pointerPosition(event),g=geometry();if(state.pointer.type==='node'){const node=state.nodes[state.pointer.index];if(!node)return;node.x=clamp(p.x/g.w,state.loopStart+.005,state.loopEnd-.005);node.y=clamp(p.y/g.h,.04,.96);updateInspector();saveState();}else if(state.pointer.type==='boundary'){if(state.pointer.side==='start')state.loopStart=clamp(p.x/g.w,.015,state.loopEnd-.08);else state.loopEnd=clamp(p.x/g.w,state.loopStart+.08,.985);updateLoopReadout();saveState();}else if(state.tool==='sculpt')sculptAt(p.x,p.y,.72);state.pointer.last=p;});
  canvas.addEventListener('pointerup',event=>{canvas.releasePointerCapture?.(event.pointerId);state.pointer=null;});canvas.addEventListener('pointercancel',()=>{state.pointer=null;});
  canvas.addEventListener('dblclick',event=>{const p=pointerPosition(event),g=geometry(),n=canvasToNormalized(p.x,p.y);state.nodes.push({id:uid('node'),x:clamp(n.x,state.loopStart+.01,state.loopEnd-.01),y:n.y,velocity:96});state.selectedNode=state.nodes.length-1;updateInspector();saveState();setStatus('New trigger node added.');});
  canvas.addEventListener('contextmenu',event=>{event.preventDefault();const p=pointerPosition(event),hit=hitTest(p.x,p.y);if(hit.type==='node')deleteNode(hit.index);});
  function deleteNode(index=state.selectedNode){if(state.nodes.length<=1){setStatus('The Loom must keep at least one trigger.');return;}state.nodes.splice(index,1);state.selectedNode=clamp(index,0,state.nodes.length-1);updateInspector();saveState();setStatus('Trigger node removed.');}
  function ensureAudio(){if(state.audio.ctx)return state.audio.ctx;const ac=new(window.AudioContext||window.webkitAudioContext)(),master=ac.createGain(),dry=ac.createGain(),wet=ac.createGain(),delay=ac.createDelay(2),feedback=ac.createGain(),compressor=ac.createDynamicsCompressor();master.gain.value=.68;dry.gain.value=1-state.space*.55;wet.gain.value=state.space*.5;delay.delayTime.value=.28;feedback.gain.value=.36;delay.connect(feedback);feedback.connect(delay);dry.connect(compressor);delay.connect(wet);wet.connect(compressor);compressor.connect(master);master.connect(ac.destination);Object.assign(state.audio,{ctx:ac,master,dry,wet,delay,feedback,compressor});return ac;}
  function periodicWave(){const ac=ensureAudio();if(state.audio.periodicWave)return state.audio.periodicWave;const harmonics=32,real=new Float32Array(harmonics+1),imag=new Float32Array(harmonics+1);for(let k=1;k<=harmonics;k++){let re=0,im=0;for(let n=0;n<POINTS;n++){const sample=state.points[n],phase=TAU*k*n/POINTS;re+=sample*Math.cos(phase);im-=sample*Math.sin(phase);}const tilt=Math.pow(1-k/(harmonics+1),1.6-state.harmonics);real[k]=re/POINTS*tilt;imag[k]=im/POINTS*tilt;}state.audio.periodicWave=ac.createPeriodicWave(real,imag,{disableNormalization:false});return state.audio.periodicWave;}
  function scheduleVoice(node,when,duration=.28){const ac=ensureAudio(),osc=ac.createOscillator(),gain=ac.createGain(),filter=ac.createBiquadFilter(),pan=ac.createStereoPanner();osc.setPeriodicWave(periodicWave());const midi=midiForNode(node),freq=440*Math.pow(2,(midi-69)/12);osc.frequency.setValueAtTime(freq,when);filter.type='lowpass';filter.frequency.setValueAtTime(650+state.harmonics*7200,when);filter.Q.value=2+state.harmonics*6;pan.pan.value=(node.x-.5)*1.4;const level=(node.velocity/127)*.22;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(Math.max(.001,level),when+.012);gain.gain.exponentialRampToValueAtTime(.0001,when+duration);osc.connect(filter);filter.connect(pan);pan.connect(gain);gain.connect(state.audio.dry);gain.connect(state.audio.delay);osc.start(when);osc.stop(when+duration+.03);}
  function zeroCrossings(){const events=[];for(let i=1;i<POINTS;i++){const a=state.points[i-1],b=state.points[i];if((a<=0&&b>0)||(a>=0&&b<0)){const f=Math.abs(a)/(Math.abs(a)+Math.abs(b)),x=((i-1)+f)/(POINTS-1);if(x>=state.loopStart&&x<=state.loopEnd)events.push(x);}}return events;}
  function schedulePerc(when,brightness=.5){const ac=ensureAudio(),length=Math.floor(ac.sampleRate*.04),buffer=ac.createBuffer(1,length,ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,3);const src=ac.createBufferSource(),filter=ac.createBiquadFilter(),gain=ac.createGain();src.buffer=buffer;filter.type='highpass';filter.frequency.value=2500+brightness*7000;gain.gain.setValueAtTime(.035+state.density*.035,when);gain.gain.exponentialRampToValueAtTime(.0001,when+.045);src.connect(filter);filter.connect(gain);gain.connect(state.audio.dry);src.start(when);}
  function scheduleLoop(startTime){const duration=60/state.tempo*4;state.audio.loopDuration=duration;const span=Math.max(.001,state.loopEnd-state.loopStart);state.nodes.slice().sort((a,b)=>a.x-b.x).forEach(node=>{if(node.x<state.loopStart||node.x>state.loopEnd)return;const ratio=(node.x-state.loopStart)/span;scheduleVoice(node,startTime+ratio*duration,.16+(1-state.density)*.34);});if(state.zeroPerc){const crosses=zeroCrossings(),stride=Math.max(1,Math.round(4-state.density*3));crosses.forEach((x,index)=>{if(index%stride)return;const ratio=(x-state.loopStart)/span;schedulePerc(startTime+ratio*duration,index/crosses.length);});}}
  function schedulerPass(){const ac=state.audio.ctx;if(!ac||!state.playing)return;while(state.audio.nextLoopTime<ac.currentTime+.35){scheduleLoop(state.audio.nextLoopTime);state.audio.nextLoopTime+=state.audio.loopDuration;}}
  async function togglePlay(){const ac=ensureAudio();if(ac.state==='suspended')await ac.resume();state.playing=!state.playing;$('playBtn').classList.toggle('active',state.playing);$('playBtn').querySelector('span').textContent=state.playing?'■':'▶';$('playBtn').querySelector('b').textContent=state.playing?'STOP':'PLAY';if(state.playing){state.audio.nextLoopTime=ac.currentTime+.06;state.audio.loopDuration=60/state.tempo*4;schedulerPass();state.audio.timer=setInterval(schedulerPass,60);setStatus('Wave geometry is generating sound.',true);}else{clearInterval(state.audio.timer);state.audio.timer=0;state.playhead=0;setStatus('Playback stopped.',false);}}
  function resetWave(){state.points=Array.from({length:POINTS},(_,i)=>{const t=i/(POINTS-1);return Math.sin(t*TAU*2)*.27+Math.sin(t*TAU*5+.8)*.09+Math.sin(t*TAU*9)*.035;});state.basePoints=state.points.slice();state.audio.periodicWave=null;saveState();setStatus('Wave geometry reset.');}
  function updateSpace(){if(!state.audio.ctx)return;state.audio.dry.gain.setTargetAtTime(1-state.space*.55,state.audio.ctx.currentTime,.02);state.audio.wet.gain.setTargetAtTime(state.space*.5,state.audio.ctx.currentTime,.02);}
  async function armMic(){if(state.mic.recorder){state.mic.recorder.stop();state.mic.stream?.getTracks().forEach(track=>track.stop());Object.assign(state.mic,{stream:null,recorder:null,chunks:[],analyser:null,data:null});$('micBtn').classList.remove('live');$('captureOrb').classList.remove('live');$('captureBtn').disabled=true;$('micBtn').querySelector('b').textContent='ARM ROLLING BUFFER';setStatus('NeuCapture disarmed.');return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),candidates=['audio/webm;codecs=opus','audio/webm','audio/ogg'],mime=candidates.find(type=>window.MediaRecorder?.isTypeSupported?.(type))||'',recorder=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream),ac=ensureAudio(),source=ac.createMediaStreamSource(stream),analyser=ac.createAnalyser();analyser.fftSize=256;source.connect(analyser);const chunks=[];recorder.ondataavailable=event=>{if(!event.data?.size)return;chunks.push({blob:event.data,time:performance.now()});const cutoff=performance.now()-6500;while(chunks.length&&chunks[0].time<cutoff)chunks.shift();};recorder.start(250);Object.assign(state.mic,{stream,recorder,chunks,analyser,data:new Uint8Array(analyser.frequencyBinCount),startTime:performance.now()});$('micBtn').classList.add('live');$('captureOrb').classList.add('live');$('captureBtn').disabled=false;$('micBtn').querySelector('b').textContent='DISARM BUFFER';setStatus('Rolling microphone buffer armed.');}catch(error){console.error(error);setStatus('Microphone permission was denied or unavailable.');}}
  function updateInputMeter(){if(!state.mic.analyser){$('inputMeter').style.width='0%';return;}state.mic.analyser.getByteTimeDomainData(state.mic.data);let sum=0;for(const value of state.mic.data){const v=(value-128)/128;sum+=v*v;}const rms=Math.sqrt(sum/state.mic.data.length);$('inputMeter').style.width=Math.min(100,rms*420)+'%';const elapsed=(performance.now()-state.mic.startTime)/1000;$('captureTimer').textContent=Math.min(5,elapsed).toFixed(1)+'s';}
  async function captureLastFive(){const rec=state.mic.recorder;if(!rec||!state.mic.chunks.length){setStatus('Arm NeuCapture and make a sound first.');return;}try{rec.requestData();await new Promise(resolve=>setTimeout(resolve,90));const recent=state.mic.chunks.filter(item=>item.time>=performance.now()-5200),blob=new Blob(recent.map(item=>item.blob),{type:rec.mimeType||'audio/webm'}),ac=ensureAudio(),buffer=await ac.decodeAudioData(await blob.arrayBuffer());addSample(buffer,`NeuCapture ${state.samples.length+1}`,'#29f3ff');setStatus(`Captured ${Math.min(5,buffer.duration).toFixed(1)} seconds as a Sample Block.`);}catch(error){console.error(error);setStatus('The browser could not decode this rolling capture. Try a slightly longer sound.');}}
  function makeDemoBuffer(){const ac=ensureAudio(),duration=1.4,buffer=ac.createBuffer(1,Math.floor(ac.sampleRate*duration),ac.sampleRate),d=buffer.getChannelData(0);for(let i=0;i<d.length;i++){const t=i/ac.sampleRate,env=Math.exp(-t*2.8);d[i]=(Math.sin(TAU*440*t)+.36*Math.sin(TAU*887*t)+.15*Math.sin(TAU*1320*t))*env*.42;if(t>.67&&t<.7)d[i]+=(Math.random()*2-1)*.28;}return buffer;}
  function peaksFor(buffer,count=160){const d=buffer.getChannelData(0),step=Math.max(1,Math.floor(d.length/count)),peaks=[];for(let i=0;i<count;i++){let min=1,max=-1;for(let j=i*step;j<Math.min(d.length,(i+1)*step);j++){min=Math.min(min,d[j]);max=Math.max(max,d[j]);}peaks.push([min,max]);}return peaks;}
  function addSample(buffer,name,color='#9b6cff'){const sample={id:uid('sample'),name,buffer,duration:buffer.duration,color,peaks:peaksFor(buffer)};state.samples.push(sample);renderSamples();return sample;}
  function renderSamples(){if(!state.samples.length){sampleShelf.innerHTML='<div class="sample-empty">NO SAMPLE BLOCKS · CAPTURE OR CREATE A DEMO</div>';return;}sampleShelf.innerHTML='';state.samples.forEach((sample,index)=>{const article=document.createElement('article');article.className='sample-block';article.draggable=true;article.dataset.sampleId=sample.id;article.style.setProperty('--sample-color',sample.color);article.innerHTML=`<header><i></i><b>${escapeHtml(sample.name)}</b><span>${sample.duration.toFixed(2)}s</span></header><canvas width="430" height="82" aria-label="${escapeHtml(sample.name)} waveform"></canvas><div class="sample-actions"><button data-preview>PREVIEW</button><button data-remove>REMOVE</button></div>`;const wave=article.querySelector('canvas');drawSampleWave(wave,sample);article.addEventListener('dragstart',event=>{article.classList.add('dragging');event.dataTransfer.setData('text/neusic-sample',sample.id);event.dataTransfer.effectAllowed='copy';});article.addEventListener('dragend',()=>article.classList.remove('dragging'));article.querySelector('[data-preview]').onclick=()=>previewSample(sample);article.querySelector('[data-remove]').onclick=()=>{state.samples.splice(index,1);renderSamples();};let slicing=false,line=null;wave.addEventListener('pointerdown',event=>{slicing=true;wave.setPointerCapture?.(event.pointerId);line=document.createElement('span');line.className='slice-line';article.appendChild(line);moveSliceLine(event,wave,line);});wave.addEventListener('pointermove',event=>{if(slicing)moveSliceLine(event,wave,line);});wave.addEventListener('pointerup',event=>{if(!slicing)return;slicing=false;wave.releasePointerCapture?.(event.pointerId);const rect=wave.getBoundingClientRect(),ratio=clamp((event.clientX-rect.left)/rect.width,.08,.92);line?.remove();sliceSample(sample,index,ratio);});sampleShelf.appendChild(article);});}
  function moveSliceLine(event,wave,line){const ar=wave.parentElement.getBoundingClientRect();line.style.left=(event.clientX-ar.left)+'px';}
  function drawSampleWave(canvasEl,sample){const c=canvasEl.getContext('2d'),w=canvasEl.width,h=canvasEl.height;c.clearRect(0,0,w,h);c.fillStyle='#03090c';c.fillRect(0,0,w,h);c.strokeStyle=sample.color;c.shadowColor=sample.color;c.shadowBlur=8;c.lineWidth=1.2;c.beginPath();sample.peaks.forEach((peak,i)=>{const x=i/(sample.peaks.length-1)*w,y1=h/2+peak[0]*h*.42,y2=h/2+peak[1]*h*.42;c.moveTo(x,y1);c.lineTo(x,y2);});c.stroke();c.shadowBlur=0;c.strokeStyle='rgba(255,255,255,.12)';c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke();}
  function previewSample(sample){const ac=ensureAudio(),src=ac.createBufferSource(),gain=ac.createGain();src.buffer=sample.buffer;gain.gain.value=.7;src.connect(gain);gain.connect(state.audio.master);src.start();setStatus(`Previewing ${sample.name}.`);}
  function sliceSample(sample,index,ratio){const ac=ensureAudio(),cut=Math.floor(sample.buffer.length*ratio),make=(start,length,name,color)=>{const b=ac.createBuffer(sample.buffer.numberOfChannels,length,sample.buffer.sampleRate);for(let ch=0;ch<b.numberOfChannels;ch++)b.copyToChannel(sample.buffer.getChannelData(ch).slice(start,start+length),ch);return{id:uid('sample'),name,buffer:b,duration:b.duration,color,peaks:peaksFor(b)};},left=make(0,cut,`${sample.name} A`,sample.color),right=make(cut,sample.buffer.length-cut,`${sample.name} B`,sample.color==='#29f3ff'?'#9b6cff':'#65ff9c');state.samples.splice(index,1,left,right);renderSamples();setStatus(`${sample.name} split into two Sample Blocks.`);}
  function unfoldSample(sample){const data=sample.buffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/POINTS)),next=[],energies=[];for(let i=0;i<POINTS;i++){let sum=0,mean=0,zc=0,prev=data[i*step]||0;for(let j=i*step;j<Math.min(data.length,(i+1)*step);j++){const v=data[j];sum+=v*v;mean+=v;if((v>=0)!==(prev>=0))zc++;prev=v;}const len=Math.max(1,Math.min(data.length,(i+1)*step)-i*step),rms=Math.sqrt(sum/len),sign=mean>=0?1:-1;next.push(clamp(sign*rms*2.5,-.92,.92));energies.push({i,rms,zc});}const max=Math.max(.001,...next.map(Math.abs));state.points=next.map(v=>v/max*.68);state.basePoints=state.points.slice();state.audio.periodicWave=null;const candidates=energies.slice(1,-1).filter((item,i,arr)=>item.rms>(arr[i-1]?.rms||0)&&item.rms>(arr[i+1]?.rms||0)).sort((a,b)=>b.rms-a.rms).slice(0,8).sort((a,b)=>a.i-b.i);state.nodes=candidates.length?candidates.map(item=>({id:uid('node'),x:clamp(item.i/(POINTS-1),state.loopStart+.01,state.loopEnd-.01),y:clamp(.5-state.points[item.i]*.42,.08,.92),velocity:clamp(Math.round(62+item.rms*170),45,127)})):state.nodes;state.selectedNode=0;updateInspector();saveState();setStatus(`${sample.name} unfolded into a playable Wave Pattern.`,state.playing);}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
  frame.addEventListener('dragover',event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';$('dropMessage').classList.add('show');});frame.addEventListener('dragleave',event=>{if(!frame.contains(event.relatedTarget))$('dropMessage').classList.remove('show');});frame.addEventListener('drop',event=>{event.preventDefault();$('dropMessage').classList.remove('show');const id=event.dataTransfer.getData('text/neusic-sample'),sample=state.samples.find(item=>item.id===id);if(sample)unfoldSample(sample);});
  function bindControls(){$('playBtn').onclick=togglePlay;$('resetBtn').onclick=resetWave;$('micBtn').onclick=armMic;$('captureBtn').onclick=captureLastFive;$('demoSampleBtn').onclick=()=>{addSample(makeDemoBuffer(),`Glass Tap ${state.samples.length+1}`,'#9b6cff');setStatus('Demo Sample Block forged.');};$('helpBtn').onclick=()=>$('helpDialog').showModal();$('deleteNodeBtn').onclick=()=>deleteNode();$('nodeVelocity').oninput=event=>{const node=selectedNode();if(!node)return;node.velocity=Number(event.target.value);updateInspector();saveState();};$('tempoInput').onchange=event=>{state.tempo=clamp(Number(event.target.value)||112,40,220);event.target.value=state.tempo;$('tempoReadout').textContent=state.tempo;saveState();};$('rootSelect').onchange=event=>{state.root=event.target.selectedIndex;updateInspector();saveState();};$('scaleSelect').onchange=event=>{state.scale=event.target.value;updateInspector();saveState();};$('zeroPerc').onchange=event=>{state.zeroPerc=event.target.checked;saveState();};$('livePreview').onchange=event=>{state.livePreview=event.target.checked;};document.querySelectorAll('.mode').forEach(button=>button.onclick=()=>{state.tool=button.dataset.tool;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b===button));canvas.style.cursor=state.tool==='nodes'?'grab':state.tool==='boundaries'?'ew-resize':'crosshair';setStatus(`${button.textContent.toLowerCase()} mode selected.`);});['harmonics','density','space','morph'].forEach(id=>{$(id).oninput=event=>{state[id]=Number(event.target.value)/100;event.target.nextElementSibling.textContent=event.target.value;if(id==='harmonics')state.audio.periodicWave=null;if(id==='space')updateSpace();if(id==='morph'){const amount=state.morph;state.points=state.points.map((point,index)=>lerp(point,state.basePoints[index]||point,amount*.025));state.audio.periodicWave=null;}saveState();};});document.addEventListener('keydown',event=>{if(event.target.matches('input,select,button'))return;if(event.code==='Space'){event.preventDefault();togglePlay();return;}const node=selectedNode();if(!node)return;if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();deleteNode();return;}const step=event.shiftKey?.02:.006;if(event.key==='ArrowLeft')node.x=clamp(node.x-step,state.loopStart+.005,state.loopEnd-.005);else if(event.key==='ArrowRight')node.x=clamp(node.x+step,state.loopStart+.005,state.loopEnd-.005);else if(event.key==='ArrowUp')node.y=clamp(node.y-step,.04,.96);else if(event.key==='ArrowDown')node.y=clamp(node.y+step,.04,.96);else return;event.preventDefault();updateInspector();saveState();});}
  loadState();bindControls();updateControls();renderSamples();addSample(makeDemoBuffer(),'Glass Tap','#9b6cff');resize();window.addEventListener('resize',resize);state.animation=requestAnimationFrame(animate);setStatus('Wave Loom Lab ready. Sculpt the wave or unfold a Sample Block.');
})();
