(() => {
  'use strict';
  if (window.NeusicExpandedExport) return;

  const R=window.NeusicWaveReliability;
  const P=()=>window.NeusicSamplePerformance;
  const TAU=Math.PI*2;
  const SCALE_STEPS={minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],dorian:[0,2,3,5,7,9,10],pentatonic:[0,3,5,7,10],chromatic:[0,1,2,3,4,5,6,7,8,9,10,11]};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  let lastRender=null;

  function midiForNode(node,core){const scale=SCALE_STEPS[core.scale]||SCALE_STEPS.minor,degree=Math.round((1-node.y)*20),octave=2+Math.floor(degree/scale.length);return 12*(octave+1)+Number(core.root||0)+scale[degree%scale.length];}
  function makeImpulse(ctx,seconds=1.8,decay=2.3){const length=Math.max(1,Math.floor(ctx.sampleRate*seconds)),buffer=ctx.createBuffer(2,length,ctx.sampleRate);for(let channel=0;channel<2;channel++){const data=buffer.getChannelData(channel);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,decay);}return buffer;}
  function cloneBuffer(ctx,source){const buffer=ctx.createBuffer(source.numberOfChannels,source.length,source.sampleRate);for(let channel=0;channel<source.numberOfChannels;channel++)buffer.copyToChannel(source.getChannelData(channel),channel);return buffer;}
  function periodicWave(ctx,points,harmonicAmount){const harmonics=32,real=new Float32Array(harmonics+1),imag=new Float32Array(harmonics+1);for(let harmonic=1;harmonic<=harmonics;harmonic++){let re=0,im=0;for(let index=0;index<points.length;index++){const phase=TAU*harmonic*index/points.length;re+=points[index]*Math.cos(phase);im-=points[index]*Math.sin(phase);}const tilt=Math.pow(1-harmonic/(harmonics+1),1.6-Number(harmonicAmount||.58));real[harmonic]=re/points.length*tilt;imag[harmonic]=im/points.length*tilt;}return ctx.createPeriodicWave(real,imag,{disableNormalization:false});}

  function graph(ctx,options){const master=ctx.createGain(),limiter=ctx.createDynamicsCompressor(),wave=ctx.createGain(),sample=ctx.createGain(),perc=ctx.createGain(),delayIn=ctx.createGain(),delay=ctx.createDelay(4),feedback=ctx.createGain(),delayWet=ctx.createGain(),reverbIn=ctx.createGain(),convolver=ctx.createConvolver(),reverbWet=ctx.createGain();master.gain.value=.82;delay.delayTime.value=.28;feedback.gain.value=.32;delayWet.gain.value=options.wet?Number(options.delayMix):0;reverbWet.gain.value=options.wet?Number(options.reverbMix):0;convolver.buffer=makeImpulse(ctx,Math.max(.3,Number(options.tail)||1.8));wave.connect(master);sample.connect(master);perc.connect(master);delayIn.connect(delay);delay.connect(feedback);feedback.connect(delay);delay.connect(delayWet);delayWet.connect(master);reverbIn.connect(convolver);convolver.connect(reverbWet);reverbWet.connect(master);master.connect(limiter);limiter.connect(ctx.destination);return{master,wave,sample,perc,delayIn,reverbIn};}

  function connectVoice(source,gain,pan,bus,g,delaySend=.15,reverbSend=.18){source.connect(pan);pan.connect(gain);gain.connect(bus);const d=g.master.context.createGain(),r=g.master.context.createGain();d.gain.value=delaySend;r.gain.value=reverbSend;gain.connect(d);d.connect(g.delayIn);gain.connect(r);r.connect(g.reverbIn);}

  function scheduleWave(ctx,g,core,node,when,waveform){const osc=ctx.createOscillator(),filter=ctx.createBiquadFilter(),gain=ctx.createGain(),pan=ctx.createStereoPanner?ctx.createStereoPanner():ctx.createGain();osc.setPeriodicWave(waveform);osc.frequency.value=440*Math.pow(2,(midiForNode(node,core)-69)/12);filter.type='lowpass';filter.frequency.value=650+Number(core.harmonics||.58)*7200;filter.Q.value=2+Number(core.harmonics||.58)*6;if(pan.pan)pan.pan.value=(node.x-.5)*1.4;const level=clamp(Number(node.velocity||96)/127*.2,.02,.24),duration=.16+(1-Number(core.density||.46))*.34;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(level,when+.012);gain.gain.exponentialRampToValueAtTime(.0001,when+duration);osc.connect(filter);filter.connect(pan);pan.connect(gain);gain.connect(g.wave);gain.connect(g.delayIn);gain.connect(g.reverbIn);osc.start(when);osc.stop(when+duration+.03);}

  function zeroCrossings(points,start,end){const result=[];for(let i=1;i<points.length;i++){if((points[i-1]<=0&&points[i]>0)||(points[i-1]>=0&&points[i]<0)){const ratio=(i-1+Math.abs(points[i-1])/(Math.abs(points[i-1])+Math.abs(points[i])||1))/(points.length-1);if(ratio>=start&&ratio<=end)result.push(ratio);}}return result;}
  function schedulePerc(ctx,g,when,brightness,density){const length=Math.floor(ctx.sampleRate*.04),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,3);const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;filter.type='highpass';filter.frequency.value=2500+brightness*7000;gain.gain.setValueAtTime(.035+density*.035,when);gain.gain.exponentialRampToValueAtTime(.0001,when+.045);source.connect(filter);filter.connect(gain);gain.connect(g.perc);source.start(when);}

  function scheduleSample(ctx,g,core,node,when,bufferCache){const performance=P(),assignment=performance.assignmentFor(node);if(!assignment.sampleId||Math.random()>assignment.probability)return;const sample=R.state.samples.find(item=>item.id===assignment.sampleId);if(!sample)return;let sourceBuffer=bufferCache.get(`${sample.id}:${assignment.reverse}`);if(!sourceBuffer){sourceBuffer=cloneBuffer(ctx,performance.renderEditedBuffer(sample,assignment.reverse));bufferCache.set(`${sample.id}:${assignment.reverse}`,sourceBuffer);}const window=performance.sliceWindow(sample,sourceBuffer,assignment.sliceId),source=ctx.createBufferSource(),gain=ctx.createGain(),pan=ctx.createStereoPanner?ctx.createStereoPanner():ctx.createGain(),rootMidi=60+Number(core.root||0),rate=clamp(Math.pow(2,(midiForNode(node,core)-rootMidi+assignment.transpose)/12),.25,4);source.buffer=sourceBuffer;source.playbackRate.value=rate;if(pan.pan)pan.pan.value=assignment.pan;const duration=Math.max(.035,Math.min(window.duration/rate,assignment.length)),level=clamp(Number(node.velocity||96)/127*.68,.03,.8);gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(level,when+.006);gain.gain.setValueAtTime(level,Math.max(when+.007,when+duration-.018));gain.gain.exponentialRampToValueAtTime(.0001,when+duration);connectVoice(source,gain,pan,g.sample,g,assignment.delaySend,assignment.reverbSend);source.start(when,window.offset,Math.max(.01,Math.min(window.duration,duration*rate)));source.stop(when+duration+.04);}

  function scheduleCycle(ctx,g,core,startTime,duration,stem,waveform,bufferCache){const span=Math.max(.001,core.loopEnd-core.loopStart),mode=R.state.engineMode;[...core.nodes].sort((a,b)=>a.x-b.x).forEach(node=>{if(node.x<core.loopStart||node.x>core.loopEnd)return;const when=startTime+(node.x-core.loopStart)/span*duration;if((stem==='mix'||stem==='wave')&&(mode==='wave'||mode==='hybrid'))scheduleWave(ctx,g,core,node,when,waveform);if((stem==='mix'||stem==='sample')&&mode!=='wave')scheduleSample(ctx,g,core,node,when,bufferCache);});if((stem==='mix'||stem==='percussion')&&core.zeroPerc){const crossings=zeroCrossings(core.points,core.loopStart,core.loopEnd),stride=Math.max(1,Math.round(4-Number(core.density||.46)*3));crossings.forEach((x,index)=>{if(index%stride)return;schedulePerc(ctx,g,startTime+(x-core.loopStart)/span*duration,index/Math.max(1,crossings.length),Number(core.density||.46));});}}

  function normalizeBuffer(buffer){let peak=0;for(let channel=0;channel<buffer.numberOfChannels;channel++){const data=buffer.getChannelData(channel);for(const value of data)peak=Math.max(peak,Math.abs(value));}if(peak<.000001||peak<=.98)return buffer;const gain=.98/peak;for(let channel=0;channel<buffer.numberOfChannels;channel++){const data=buffer.getChannelData(channel);for(let i=0;i<data.length;i++)data[i]*=gain;}return buffer;}

  async function renderStem(stem,options){const core=R.loom?.state;if(!core)throw new Error('The Wave Loom engine is unavailable.');const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline)throw new Error('Offline audio rendering is not available in this browser.');const sampleRate=Number(options.sampleRate),bars=Number(options.bars),cycle=60/Number(core.tempo||112)*4,tail=options.seamless?0:Number(options.tail),duration=cycle*bars+tail,ctx=new Offline(2,Math.ceil(duration*sampleRate),sampleRate),g=graph(ctx,options),waveform=periodicWave(ctx,core.points,core.harmonics),bufferCache=new Map();for(let bar=0;bar<bars;bar++)scheduleCycle(ctx,g,core,bar*cycle,cycle,stem,waveform,bufferCache);let rendered=await ctx.startRendering();if(options.normalize)rendered=normalizeBuffer(rendered);return rendered;}

  function encodeWav(buffer,bitDepth=24){const channels=buffer.numberOfChannels,sampleRate=buffer.sampleRate,frames=buffer.length,bytes=bitDepth===24?3:2,blockAlign=channels*bytes,array=new ArrayBuffer(44+frames*blockAlign),view=new DataView(array),write=(offset,text)=>{for(let i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i));};write(0,'RIFF');view.setUint32(4,36+frames*blockAlign,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*blockAlign,true);view.setUint16(32,blockAlign,true);view.setUint16(34,bitDepth,true);write(36,'data');view.setUint32(40,frames*blockAlign,true);let offset=44;for(let frame=0;frame<frames;frame++){for(let channel=0;channel<channels;channel++){const sample=clamp(buffer.getChannelData(channel)[frame],-1,1);if(bitDepth===24){let value=Math.round(sample<0?sample*0x800000:sample*0x7fffff);if(value<0)value+=0x1000000;view.setUint8(offset,value&255);view.setUint8(offset+1,(value>>8)&255);view.setUint8(offset+2,(value>>16)&255);offset+=3;}else{view.setInt16(offset,sample<0?sample*0x8000:sample*0x7fff,true);offset+=2;}}}return new Blob([array],{type:'audio/wav'});}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}

  function optionsFromDialog(){const d=document.getElementById('expandedExportDialog');return{stem:d.querySelector('[data-export-stem]').value,bars:Number(d.querySelector('[data-export-bars]').value),sampleRate:Number(d.querySelector('[data-export-rate]').value),bitDepth:Number(d.querySelector('[data-export-depth]').value),wet:d.querySelector('[data-export-wet]').checked,delayMix:Number(d.querySelector('[data-export-delay]').value)/100,reverbMix:Number(d.querySelector('[data-export-reverb]').value)/100,tail:Number(d.querySelector('[data-export-tail]').value),normalize:d.querySelector('[data-export-normalize]').checked,seamless:d.querySelector('[data-export-seamless]').checked};}
  function filename(stem,options){const stamp=new Date().toISOString().slice(0,19).replace(/[:T]/g,'-');return`neusic-wave-${stem}-${R.loom.state.tempo}bpm-${options.bitDepth}bit-${stamp}.wav`;}

  async function renderSelection(sendToStudio=false){const button=document.querySelector(sendToStudio?'[data-export-studio]':'[data-export-render]'),options=optionsFromDialog(),original=button.textContent;button.disabled=true;button.textContent='RENDERING…';R.setStatus(`Rendering ${options.stem} at ${options.sampleRate/1000}kHz / ${options.bitDepth}-bit…`,'live');try{if(options.stem==='stems'){const stems=['wave','sample','percussion','mix'];for(const stem of stems){const rendered=await renderStem(stem,options);download(encodeWav(rendered,options.bitDepth),filename(stem,options));lastRender={buffer:rendered,stem,options};}R.setStatus('Wave, sample, percussion, and mix stems exported.','live');}else{const rendered=await renderStem(options.stem,options);lastRender={buffer:rendered,stem:options.stem,options};if(sendToStudio){await window.NeusicStudioTransfer.sendBuffer(rendered,{name:`Wave Loom ${options.stem}`,metadata:{kind:'expanded-export',options}});}else{download(encodeWav(rendered,options.bitDepth),filename(options.stem,options));R.setStatus(`${options.stem.toUpperCase()} export complete.`,'live');}}}catch(error){console.error(error);R.setStatus(error.message||'Export failed.','error');}finally{button.disabled=false;button.textContent=original;}}

  function buildDialog(){if(document.getElementById('expandedExportDialog'))return;const dialog=document.createElement('dialog');dialog.id='expandedExportDialog';dialog.className='expanded-export-dialog';dialog.innerHTML=`<form method="dialog"><header><div><span class="kicker">OFFLINE PRODUCTION RENDER</span><h2>Expanded Export</h2></div><button value="cancel" aria-label="Close export">×</button></header><div class="export-grid"><label>CONTENT<select data-export-stem><option value="mix">FULL MIX</option><option value="wave">WAVE STEM</option><option value="sample">SAMPLE STEM</option><option value="percussion">PERCUSSION STEM</option><option value="stems">ALL STEMS</option></select></label><label>LENGTH<select data-export-bars><option value="1">1 BAR</option><option value="2">2 BARS</option><option value="4" selected>4 BARS</option><option value="8">8 BARS</option><option value="16">16 BARS</option></select></label><label>SAMPLE RATE<select data-export-rate><option value="44100">44.1 KHZ</option><option value="48000" selected>48 KHZ</option></select></label><label>BIT DEPTH<select data-export-depth><option value="16">16-BIT</option><option value="24" selected>24-BIT</option></select></label><label>DELAY MIX<input data-export-delay type="range" min="0" max="100" value="28"><output>28%</output></label><label>REVERB MIX<input data-export-reverb type="range" min="0" max="100" value="24"><output>24%</output></label><label>TAIL<select data-export-tail><option value="0">NONE</option><option value="1.5" selected>1.5 SEC</option><option value="3">3 SEC</option><option value="6">6 SEC</option></select></label><label class="export-check"><input data-export-wet type="checkbox" checked><span>INCLUDE EFFECTS</span></label><label class="export-check"><input data-export-normalize type="checkbox" checked><span>NORMALIZE</span></label><label class="export-check"><input data-export-seamless type="checkbox"><span>SEAMLESS LOOP</span></label></div><p>Rendering is performed locally with OfflineAudioContext. No audio is uploaded.</p><footer><button data-export-studio type="button">SEND MIX TO STUDIO</button><button data-export-render class="primary" type="button">RENDER WAV</button></footer></form>`;document.body.appendChild(dialog);dialog.querySelectorAll('input[type="range"]').forEach(input=>input.addEventListener('input',()=>input.nextElementSibling.textContent=`${input.value}%`));dialog.querySelector('[data-export-render]').onclick=()=>renderSelection(false);dialog.querySelector('[data-export-studio]').onclick=()=>renderSelection(true);}
  function bindExportButton(){const button=document.getElementById('exportBtn');if(!button)return;button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();document.getElementById('expandedExportDialog')?.showModal();},true);button.textContent='EXPORT / STEMS';}

  const api={renderStem,encodeWav,renderSelection,get lastRender(){return lastRender;}};window.NeusicExpandedExport=api;R.ready.then(value=>{if(value){buildDialog();bindExportButton();}});
})();