(() => {
  'use strict';
  if(window.__wavePolish)return;window.__wavePolish=true;
  const agentCss=document.createElement('link');agentCss.rel='stylesheet';agentCss.href='../css/shared/neusic-agent.css?v=1';if(!document.querySelector('link[href*="css/shared/neusic-agent.css"]'))document.head.appendChild(agentCss);
  if(!document.querySelector('script[src*="scripts/shared/neusic-agent.js"]')){const agentScript=document.createElement('script');agentScript.src='../scripts/shared/neusic-agent.js?v=1';agentScript.defer=true;document.body.appendChild(agentScript);}
  const dock=document.createElement('nav');dock.className='wave-mobile-dock';dock.setAttribute('aria-label','Neusic Wave mobile actions');dock.innerHTML='<button data-wave-action="capture">CAPTURE</button><button class="active" data-wave-action="sculpt">SCULPT</button><button data-wave-action="nodes">NODES</button><button data-wave-action="forge">FORGE</button>';document.body.appendChild(dock);
  dock.addEventListener('click',event=>{const action=event.target.closest('[data-wave-action]')?.dataset.waveAction;if(!action)return;dock.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.waveAction===action));if(action==='capture'){document.querySelector('.capture-rail')?.scrollIntoView({behavior:'smooth'});document.getElementById('micBtn')?.focus();return}if(action==='forge'){document.querySelector('.forge')?.scrollIntoView({behavior:'smooth'});return}document.querySelector(`[data-tool="${action}"]`)?.click();document.querySelector('.loom-stage')?.scrollIntoView({behavior:'smooth'});});
  const onboarding=document.createElement('div');onboarding.className='wave-onboarding';onboarding.innerHTML='<div class="wave-onboarding-card"><small>WELCOME TO NEUSIC WAVE</small><h2>Shape music with the wave.</h2><p>Start with a Live Loop transfer, upload a sample, or arm the microphone. Every gesture can change timing, pitch, harmony, rhythm, or sample playback.</p><div class="wave-steps"><span><b>01 · CAPTURE</b>Record or load a sound object.</span><span><b>02 · REFINE</b>Trim, slice, map, and unfold it.</span><span><b>03 · TRANSFER</b>Send the result into Neusic Lab.</span></div><div class="wave-onboarding-actions"><button data-start-wave>START SCULPTING</button><a href="../studio/">OPEN NEUSIC LAB</a></div></div>';document.body.appendChild(onboarding);
  let seen=false;try{seen=localStorage.getItem('neusic-wave-onboarding')==='1'}catch(_){}if(!seen)onboarding.classList.add('open');
  onboarding.querySelector('[data-start-wave]').addEventListener('click',()=>{onboarding.classList.remove('open');try{localStorage.setItem('neusic-wave-onboarding','1')}catch(_){}document.querySelector('[data-tool="sculpt"]')?.click()});
  document.addEventListener('keydown',event=>{if(event.key==='Escape')onboarding.classList.remove('open')});
  document.querySelectorAll('button,input,select').forEach(element=>{if(!element.getAttribute('aria-label')){const text=element.textContent?.trim()||element.previousSibling?.textContent?.trim();if(text)element.setAttribute('aria-label',text.slice(0,80));}});
})();