(() => {
  'use strict';
  if(window.__wavePolish)return;window.__wavePolish=true;
  const dock=document.createElement('nav');dock.className='wave-mobile-dock';dock.setAttribute('aria-label','Wave Loom mobile actions');dock.innerHTML='<button data-wave-action="capture">CAPTURE</button><button class="active" data-wave-action="sculpt">SCULPT</button><button data-wave-action="nodes">NODES</button><button data-wave-action="forge">FORGE</button>';document.body.appendChild(dock);
  dock.addEventListener('click',event=>{const action=event.target.closest('[data-wave-action]')?.dataset.waveAction;if(!action)return;dock.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.waveAction===action));if(action==='capture'){document.querySelector('.capture-rail')?.scrollIntoView({behavior:'smooth'});document.getElementById('micBtn')?.focus();return}if(action==='forge'){document.querySelector('.forge')?.scrollIntoView({behavior:'smooth'});return}document.querySelector(`[data-tool="${action}"]`)?.click();document.querySelector('.loom-stage')?.scrollIntoView({behavior:'smooth'});});
  const onboarding=document.createElement('div');onboarding.className='wave-onboarding';onboarding.innerHTML='<div class="wave-onboarding-card"><small>WELCOME TO WAVE LOOM</small><h2>Shape music with the wave.</h2><p>Start with the demo sample or arm your microphone. Every gesture changes timing, pitch, harmony, or rhythm.</p><div class="wave-steps"><span><b>01 · CAPTURE</b>Record or load a sound block.</span><span><b>02 · UNFOLD</b>Drag the block into the Loom.</span><span><b>03 · SCULPT</b>Move the wave and trigger nodes.</span></div><div class="wave-onboarding-actions"><button data-start-wave>START SCULPTING</button><a href="../studio/">OPEN CLASSIC STUDIO</a></div></div>';document.body.appendChild(onboarding);
  let seen=false;try{seen=localStorage.getItem('neusic-wave-onboarding')==='1'}catch(_){}if(!seen)onboarding.classList.add('open');
  onboarding.querySelector('[data-start-wave]').addEventListener('click',()=>{onboarding.classList.remove('open');try{localStorage.setItem('neusic-wave-onboarding','1')}catch(_){}document.querySelector('[data-tool="sculpt"]')?.click()});
  document.addEventListener('keydown',event=>{if(event.key==='Escape')onboarding.classList.remove('open')});
  document.querySelectorAll('button,input,select').forEach(el=>{if(!el.getAttribute('aria-label')){const text=el.textContent?.trim()||el.previousSibling?.textContent?.trim();if(text)el.setAttribute('aria-label',text.slice(0,80));}});
})();