(() => {
'use strict';
const MODES={
 loom:{title:'The Wave Loom',eyebrow:'WAVE-NATIVE INSTRUMENT',description:'Sculpt sound, timing and harmony directly. Switch modes without leaving the project.',panel:null,engine:'WAVE',inspector:'Wave controls',copy:'The wave is the instrument. Drag nodes for timing and pitch, sculpt the surface for harmonic shape, then move into Arrange or Mix without rebuilding the idea.'},
 arrange:{title:'Arrangement Field',eyebrow:'SONG FORM & TIMELINE',description:'The complete Neusic arranger, tracks, sections, clips and project workflow—focused into one canvas.',panel:null,engine:'DAW',inspector:'Arrangement context',copy:'Build the full record with real Neusic tracks, clips, sections, ripple editing, buses, autosave and offline export.'},
 perform:{title:'Performance Surface',eyebrow:'PADS, PATTERNS & LIVE PLAY',description:'Trigger drums and patterns through the working Neusic performance engine.',panel:'drums',engine:'DAW',inspector:'Performance context',copy:'Finger-drum, shape patterns and route the result into real timeline tracks without leaving this focus mode.'},
 piano:{title:'Instrument Editor',eyebrow:'MIDI COMPOSITION',description:'Piano Roll v2, scale tools, chords, ghost notes, velocity and clip-aware MIDI editing.',panel:'piano',engine:'MIDI',inspector:'MIDI context',copy:'Write detailed MIDI phrases with the completed Piano Roll while the same clips remain playable in Arrange and export.'},
 record:{title:'NeuCapture Studio',eyebrow:'AUDIO & MIDI CAPTURE',description:'Use the working microphone, managed takes, quick comping and MIDI input systems.',panel:'rec',engine:'AUDIO',inspector:'Capture context',copy:'Record into real Neusic tracks, preserve alternate takes and move directly into arrangement or mixing.'},
 mix:{title:'Spatial Mix Environment',eyebrow:'ROUTING, EFFECTS & HEADROOM',description:'Use real buses, returns, inserts, sends, meters and bounce-to-audio in a focused mixer view.',panel:'mixer',engine:'MIX',inspector:'Mix context',copy:'Balance the same session through the working Neusic mixer. Bus routing, returns, effects and export remain fully connected.'}
};
const EXT_CSS=['13-workspace-ux.css','14-production-integrity.css','15-mobile-first.css','16-project-safety.css','17a-studio-foundation.css','17b-studio-navigation.css','17c-studio-controls.css','17d-studio-mixer-mobile.css','18-producer-flow.css','19-professional-arranger.css','20a-hyperreal-shell.css','20b-hyperreal-tracks.css','20c-hyperreal-creator.css','21-production-copilot.css','22-premium-studio.css','23-recording-mix-workflow.css','24-piano-roll-v2.css'];
const EXT_JS=['22-workspace-ux.js','23-production-integrity.js','24-mobile-first.js','25-project-safety.js','26-producer-flow.js','27-producer-flow-hardening.js','28-professional-arranger.js','29-arranger-recovery-sync.js','30-track-engine.js','31-midi-clips.js','32-track-workspace.js','33-production-copilot.js','34-theme-personalization.js','35-recording-mix-workflow.js','36-piano-roll-v2.js'];
const stage=document.querySelector('.stage'),loomFrame=document.getElementById('loomFrame'),studioFrame=document.getElementById('studioFrame');
const modeButtons=[...document.querySelectorAll('[data-mode]')],$=id=>document.getElementById(id);
let currentMode='loom',studioReady=false,loomReady=false,loadingExtensions=false,prepareTimer=0;
function studioCore(){try{return studioFrame.contentWindow||null;}catch(_){return null;}}
function injectFrameStyle(win,type){try{const doc=win.document;if(!doc||doc.getElementById('neusic-v2-host-style'))return;const style=doc.createElement('style');style.id='neusic-v2-host-style';style.textContent=type==='studio'?`#topbar,#toolbar,.creator-credit,[data-neusic-creator]{display:none!important}html,body,#app{height:100%!important;min-height:100%!important}body{overflow:hidden!important}#main{min-height:0!important}.theme-toggle,.copilot-toggle{z-index:50!important}@media(max-width:850px){#mobile-nav{display:none!important}#sidebar{display:none!important}#center{width:100%!important}.dpanel{padding-bottom:18px!important}}`:`.topbar,.creator-credit,[data-neusic-creator]{display:none!important}body{padding-top:0!important}.shell,.app,.workspace{min-height:100%!important}`;doc.head.appendChild(style);}catch(_){}}
function loadScript(doc,src){return new Promise((resolve,reject)=>{if(doc.querySelector(`script[data-v2-src="${src}"],script[src$="${src}"]`))return resolve();const script=doc.createElement('script');script.src=`js/${src}`;script.dataset.v2Src=src;script.onload=resolve;script.onerror=()=>reject(new Error(src));doc.body.appendChild(script);});}
async function loadStudioExtensions(){if(studioReady||loadingExtensions)return studioReady;const core=studioCore(),doc=core?.document;if(!doc?.body)return false;loadingExtensions=true;try{EXT_CSS.forEach(name=>{if(doc.querySelector(`link[data-v2-href="${name}"],link[href$="${name}"]`))return;const link=doc.createElement('link');link.rel='stylesheet';link.href=`css/${name}`;link.dataset.v2Href=name;doc.head.appendChild(link);});for(const name of EXT_JS)await loadScript(doc,name);injectFrameStyle(core,'studio');studioReady=true;$('loadingPanel').classList.add('hidden');if(currentMode!=='loom')applyStudioMode(currentMode);return true;}catch(error){console.error('Studio v2 engine load failed',error);$('loadingMessage').textContent='The production engine could not finish loading. Open Classic Studio below.';$('loadingPanel').classList.add('error');return false;}finally{loadingExtensions=false;}}
function prepareLoom(){try{injectFrameStyle(loomFrame.contentWindow,'loom');loomReady=true;if(currentMode==='loom')$('loadingPanel').classList.add('hidden');return true;}catch(_){return false;}}
function ensurePrepared(){clearInterval(prepareTimer);let tries=0;prepareTimer=setInterval(()=>{tries++;loadStudioExtensions();prepareLoom();if((studioReady&&loomReady)||tries>100)clearInterval(prepareTimer);},160);}
function drawerIsOpen(core){return !!core?.document?.getElementById('drawer')?.classList.contains('open');}
function applyStudioMode(mode){const core=studioCore();if(!core||!studioReady)return;const config=MODES[mode];try{if(config.panel){core.openDrawer?.(config.panel);core.document.getElementById('drawer')?.classList.add('open');}else if(drawerIsOpen(core)){core.toggleDrawer?.();if(drawerIsOpen(core))core.document.getElementById('drawer')?.classList.remove('open');}core.dispatchEvent?.(new CustomEvent('neusic:focus-mode',{detail:{mode}}));}catch(_){}}
function activateMode(mode){if(!MODES[mode])return;currentMode=mode;const config=MODES[mode];modeButtons.forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));document.querySelectorAll('[data-mode-target]').forEach(button=>button.classList.toggle('active',button.dataset.modeTarget===mode));$('modeTitle').textContent=config.title;$('modeEyebrow').textContent=config.eyebrow;$('modeDescription').textContent=config.description;$('contextMode').textContent=mode.toUpperCase();$('engineType').textContent=config.engine;$('inspectorTitle').textContent=config.inspector;$('inspectorCopy').textContent=config.copy;const useLoom=mode==='loom';loomFrame.classList.toggle('active',useLoom);studioFrame.classList.toggle('active',!useLoom);$('engineState').textContent=useLoom?'LOOM READY':studioReady?'PRODUCTION ENGINE':'LOADING ENGINE';$('engineLed').style.background=useLoom?'var(--green)':'var(--cyan)';if(useLoom)prepareLoom();else{if(!studioReady)$('loadingPanel').classList.remove('hidden');loadStudioExtensions().then(()=>applyStudioMode(mode));}try{localStorage.setItem('neusic-studio-v2-mode',mode);}catch(_){}}
function clickInside(frame,selector){try{frame.contentWindow?.document?.querySelector(selector)?.click();return true;}catch(_){return false;}}
function callCore(name,...args){const core=studioCore();try{if(typeof core?.[name]==='function')return core[name](...args);}catch(_){}}
function clickCore(selector){try{studioCore()?.document?.querySelector(selector)?.click();}catch(_){}}
function command(name){if(currentMode==='loom'){if(name==='play')return clickInside(loomFrame,'#playBtn');if(name==='rewind')return clickInside(loomFrame,'#resetBtn');if(name==='record')return clickInside(loomFrame,'#captureBtn,#captureButton,[data-action="capture"]');}const actions={play:()=>callCore('togglePlay'),rewind:()=>callCore('rewind'),record:()=>callCore('toggleRecord'),save:()=>callCore('saveProjectToFile'),export:()=>callCore('exportWavFile'),undo:()=>callCore('undo'),redo:()=>callCore('redo'),theme:()=>{if(callCore('openThemePanel')===undefined)clickCore('#theme-toggle,[data-theme-toggle]');},copilot:()=>{if(callCore('openCopilot')===undefined)clickCore('[data-copilot-toggle],#copilot-toggle');},effects:()=>{activateMode('mix');setTimeout(()=>callCore('openDrawer','fx'),120);}};actions[name]?.();}
function createTrack(type){const core=studioCore();if(!core||!studioReady){activateMode('arrange');return;}try{const names={midi:'New Instrument',beat:'New Drum Track',bus:'New Bus',return:'New Return',audio:'New Audio Track'};const track=core.NeusicTracks?.create?.({type,name:names[type]||'New Track'});if(!track&&type==='audio')core.addTrack?.();core.renderTracks?.();core.toast?.(`${type} track created`);activateMode('arrange');}catch(error){console.warn('Track creation failed',error);}}
function togglePanel(side){stage.classList.toggle(`${side}-open`);}
document.addEventListener('click',event=>{const mode=event.target.closest('[data-mode]')?.dataset.mode;if(mode)activateMode(mode);const target=event.target.closest('[data-mode-target]')?.dataset.modeTarget;if(target)activateMode(target);const panel=event.target.closest('[data-panel]')?.dataset.panel;if(panel)togglePanel(panel);const action=event.target.closest('[data-command]')?.dataset.command;if(action)command(action);const type=event.target.closest('[data-create]')?.dataset.create;if(type)createTrack(type);});
document.addEventListener('keydown',event=>{if(event.target?.matches?.('input,textarea,select,[contenteditable="true"]'))return;if(event.code==='Space'){event.preventDefault();command('play');return;}const mode=['loom','arrange','perform','piano','record','mix'][Number(event.key)-1];if(mode)activateMode(mode);if(event.key==='[')togglePanel('left');if(event.key===']')togglePanel('right');});
function syncStatus(){const core=studioCore();if(core&&studioReady){try{const doc=core.document,state=core.S||{},tracks=state.tracks||[];$('timeDisplay').textContent=doc.getElementById('time-disp')?.textContent||'00:00.000';$('bpmDisplay').textContent=doc.getElementById('bpm-disp')?.textContent||state.bpm||120;$('projectName').textContent=state.projectName||state.name||'Untitled Neusic Session';$('trackCount').textContent=String(tracks.length).padStart(2,'0');$('clipCount').textContent=String(tracks.reduce((sum,track)=>sum+(track.clips?.length||0),0)).padStart(2,'0');$('playButton').textContent=state.playing?'Ⅱ':'▶';$('playButton').classList.toggle('playing',!!state.playing);$('recordButton').classList.toggle('recording',!!state.recording);}catch(_){}}if(currentMode==='loom'){try{const doc=loomFrame.contentWindow.document;$('bpmDisplay').textContent=doc.getElementById('tempoReadout')?.textContent||$('bpmDisplay').textContent;const playing=doc.getElementById('playBtn')?.classList.contains('active')||/pause/i.test(doc.getElementById('playBtn')?.textContent||'');$('playButton').classList.toggle('playing',playing);}catch(_){}}}
studioFrame.addEventListener('load',()=>{studioReady=false;loadStudioExtensions();});loomFrame.addEventListener('load',prepareLoom);window.addEventListener('resize',()=>{if(window.innerWidth<850)stage.classList.remove('left-open','right-open');});ensurePrepared();setInterval(syncStatus,250);let saved='loom';try{saved=localStorage.getItem('neusic-studio-v2-mode')||'loom';}catch(_){}activateMode(MODES[saved]?saved:'loom');
})();
